- name: Installing required packages to server
  apt:
    name:
      - nginx
      - apache2
      - mysql-server
      - phpmyadmin
      - libapache2-mod-php8.1
    state: latest

- name: Enabling apache2 service.
  service:
    name: apache2
    state: started
    enabled: true


- name: Copy html file to server
  copy:
    src: default_my.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: import phpmyadmin apache.conf to apache2.conf
  lineinfile:
    path: /etc/apache2/apache2.conf
    line: include /etc/phpmyadmin/apache.conf
    state: present
    regexp: '^include /etc/phpmyadmin/apache\.conf$'

